[package]
name = "molecules"
version = "0.1.0"
edition = "2024"
default-run = "molecules"

[dependencies]
fixed = "1.29.0"
glam = "0.30.9"
nalgebra = "0.33.2"
ndarray = "0.16.1"
quad-rand = "0.2.3"
raylib = "5.5.1"
